platforms:
  android:
    incrementVersionCode: true

    manifest:
      - file: AndroidManifest.xml
        target: manifest/application
        attrs:
          android:name: chan.dev.autoBuild

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <queries>
              <intent>
                  <action android:name="android.intent.action.MAIN" />
                  <category android:name="android.intent.category.LAUNCHER" />
              </intent>
          </queries>
    gradle:
      - file: app/build.gradle
        target:
          dependencies:
        insert: |
          implementation "com.stripe:stripe-java:20.133.0"
    res:
      - path: raw
        file: config.json
        text: |
          {
            "value": true
          }
      - path: drawable
        file: icon.png
        source: ./public/assets/icon/icon.png